// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapacket.proto

package com.wncud.protobuf;

public final class DataPacketMsg {
  private DataPacketMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.DataPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string topic = 1;</code>
     */
    boolean hasTopic();
    /**
     * <code>required string topic = 1;</code>
     */
    String getTopic();
    /**
     * <code>required string topic = 1;</code>
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>required int64 collectTime = 2;</code>
     */
    boolean hasCollectTime();
    /**
     * <code>required int64 collectTime = 2;</code>
     */
    long getCollectTime();

    /**
     * <code>required string host = 3;</code>
     */
    boolean hasHost();
    /**
     * <code>required string host = 3;</code>
     */
    String getHost();
    /**
     * <code>required string host = 3;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>required string path = 4;</code>
     */
    boolean hasPath();
    /**
     * <code>required string path = 4;</code>
     */
    String getPath();
    /**
     * <code>required string path = 4;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <code>required int64 position = 5;</code>
     */
    boolean hasPosition();
    /**
     * <code>required int64 position = 5;</code>
     */
    long getPosition();

    /**
     * <code>repeated string dataMessage = 6;</code>
     */
    com.google.protobuf.ProtocolStringList
        getDataMessageList();
    /**
     * <code>repeated string dataMessage = 6;</code>
     */
    int getDataMessageCount();
    /**
     * <code>repeated string dataMessage = 6;</code>
     */
    String getDataMessage(int index);
    /**
     * <code>repeated string dataMessage = 6;</code>
     */
    com.google.protobuf.ByteString
        getDataMessageBytes(int index);
  }
  /**
   * Protobuf type {@code tutorial.DataPacket}
   */
  public static final class DataPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.DataPacket)
      DataPacketOrBuilder {
    // Use DataPacket.newBuilder() to construct.
    private DataPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DataPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DataPacket defaultInstance;
    public static DataPacket getDefaultInstance() {
      return defaultInstance;
    }

    public DataPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DataPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              topic_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              collectTime_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              host_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              path_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              position_ = input.readInt64();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                dataMessage_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              dataMessage_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          dataMessage_ = dataMessage_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wncud.protobuf.DataPacketMsg.internal_static_tutorial_DataPacket_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wncud.protobuf.DataPacketMsg.internal_static_tutorial_DataPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wncud.protobuf.DataPacketMsg.DataPacket.class, com.wncud.protobuf.DataPacketMsg.DataPacket.Builder.class);
    }

    public static com.google.protobuf.Parser<DataPacket> PARSER =
        new com.google.protobuf.AbstractParser<DataPacket>() {
      public DataPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataPacket(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<DataPacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TOPIC_FIELD_NUMBER = 1;
    private Object topic_;
    /**
     * <code>required string topic = 1;</code>
     */
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string topic = 1;</code>
     */
    public String getTopic() {
      Object ref = topic_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          topic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string topic = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLLECTTIME_FIELD_NUMBER = 2;
    private long collectTime_;
    /**
     * <code>required int64 collectTime = 2;</code>
     */
    public boolean hasCollectTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 collectTime = 2;</code>
     */
    public long getCollectTime() {
      return collectTime_;
    }

    public static final int HOST_FIELD_NUMBER = 3;
    private Object host_;
    /**
     * <code>required string host = 3;</code>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string host = 3;</code>
     */
    public String getHost() {
      Object ref = host_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          host_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string host = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATH_FIELD_NUMBER = 4;
    private Object path_;
    /**
     * <code>required string path = 4;</code>
     */
    public boolean hasPath() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string path = 4;</code>
     */
    public String getPath() {
      Object ref = path_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          path_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string path = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSITION_FIELD_NUMBER = 5;
    private long position_;
    /**
     * <code>required int64 position = 5;</code>
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 position = 5;</code>
     */
    public long getPosition() {
      return position_;
    }

    public static final int DATAMESSAGE_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList dataMessage_;
    /**
     * <code>repeated string dataMessage = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDataMessageList() {
      return dataMessage_;
    }
    /**
     * <code>repeated string dataMessage = 6;</code>
     */
    public int getDataMessageCount() {
      return dataMessage_.size();
    }
    /**
     * <code>repeated string dataMessage = 6;</code>
     */
    public String getDataMessage(int index) {
      return dataMessage_.get(index);
    }
    /**
     * <code>repeated string dataMessage = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDataMessageBytes(int index) {
      return dataMessage_.getByteString(index);
    }

    private void initFields() {
      topic_ = "";
      collectTime_ = 0L;
      host_ = "";
      path_ = "";
      position_ = 0L;
      dataMessage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTopic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCollectTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTopicBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, collectTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPathBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, position_);
      }
      for (int i = 0; i < dataMessage_.size(); i++) {
        output.writeBytes(6, dataMessage_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTopicBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, collectTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPathBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, position_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < dataMessage_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(dataMessage_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getDataMessageList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.wncud.protobuf.DataPacketMsg.DataPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wncud.protobuf.DataPacketMsg.DataPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wncud.protobuf.DataPacketMsg.DataPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wncud.protobuf.DataPacketMsg.DataPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wncud.protobuf.DataPacketMsg.DataPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wncud.protobuf.DataPacketMsg.DataPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.wncud.protobuf.DataPacketMsg.DataPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.wncud.protobuf.DataPacketMsg.DataPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.wncud.protobuf.DataPacketMsg.DataPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.wncud.protobuf.DataPacketMsg.DataPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.wncud.protobuf.DataPacketMsg.DataPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.DataPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.DataPacket)
        com.wncud.protobuf.DataPacketMsg.DataPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wncud.protobuf.DataPacketMsg.internal_static_tutorial_DataPacket_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wncud.protobuf.DataPacketMsg.internal_static_tutorial_DataPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wncud.protobuf.DataPacketMsg.DataPacket.class, com.wncud.protobuf.DataPacketMsg.DataPacket.Builder.class);
      }

      // Construct using com.wncud.protobuf.DataPacketMsg.DataPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        topic_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        collectTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        host_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        position_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        dataMessage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wncud.protobuf.DataPacketMsg.internal_static_tutorial_DataPacket_descriptor;
      }

      public com.wncud.protobuf.DataPacketMsg.DataPacket getDefaultInstanceForType() {
        return com.wncud.protobuf.DataPacketMsg.DataPacket.getDefaultInstance();
      }

      public com.wncud.protobuf.DataPacketMsg.DataPacket build() {
        com.wncud.protobuf.DataPacketMsg.DataPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wncud.protobuf.DataPacketMsg.DataPacket buildPartial() {
        com.wncud.protobuf.DataPacketMsg.DataPacket result = new com.wncud.protobuf.DataPacketMsg.DataPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.topic_ = topic_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.collectTime_ = collectTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.host_ = host_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.path_ = path_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.position_ = position_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          dataMessage_ = dataMessage_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.dataMessage_ = dataMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wncud.protobuf.DataPacketMsg.DataPacket) {
          return mergeFrom((com.wncud.protobuf.DataPacketMsg.DataPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wncud.protobuf.DataPacketMsg.DataPacket other) {
        if (other == com.wncud.protobuf.DataPacketMsg.DataPacket.getDefaultInstance()) return this;
        if (other.hasTopic()) {
          bitField0_ |= 0x00000001;
          topic_ = other.topic_;
          onChanged();
        }
        if (other.hasCollectTime()) {
          setCollectTime(other.getCollectTime());
        }
        if (other.hasHost()) {
          bitField0_ |= 0x00000004;
          host_ = other.host_;
          onChanged();
        }
        if (other.hasPath()) {
          bitField0_ |= 0x00000008;
          path_ = other.path_;
          onChanged();
        }
        if (other.hasPosition()) {
          setPosition(other.getPosition());
        }
        if (!other.dataMessage_.isEmpty()) {
          if (dataMessage_.isEmpty()) {
            dataMessage_ = other.dataMessage_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureDataMessageIsMutable();
            dataMessage_.addAll(other.dataMessage_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTopic()) {
          
          return false;
        }
        if (!hasCollectTime()) {
          
          return false;
        }
        if (!hasHost()) {
          
          return false;
        }
        if (!hasPath()) {
          
          return false;
        }
        if (!hasPosition()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wncud.protobuf.DataPacketMsg.DataPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wncud.protobuf.DataPacketMsg.DataPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object topic_ = "";
      /**
       * <code>required string topic = 1;</code>
       */
      public boolean hasTopic() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public String getTopic() {
        Object ref = topic_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            topic_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public Builder setTopic(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public Builder clearTopic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }

      private long collectTime_ ;
      /**
       * <code>required int64 collectTime = 2;</code>
       */
      public boolean hasCollectTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 collectTime = 2;</code>
       */
      public long getCollectTime() {
        return collectTime_;
      }
      /**
       * <code>required int64 collectTime = 2;</code>
       */
      public Builder setCollectTime(long value) {
        bitField0_ |= 0x00000002;
        collectTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 collectTime = 2;</code>
       */
      public Builder clearCollectTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        collectTime_ = 0L;
        onChanged();
        return this;
      }

      private Object host_ = "";
      /**
       * <code>required string host = 3;</code>
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string host = 3;</code>
       */
      public String getHost() {
        Object ref = host_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            host_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string host = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string host = 3;</code>
       */
      public Builder setHost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 3;</code>
       */
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000004);
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 3;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        host_ = value;
        onChanged();
        return this;
      }

      private Object path_ = "";
      /**
       * <code>required string path = 4;</code>
       */
      public boolean hasPath() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string path = 4;</code>
       */
      public String getPath() {
        Object ref = path_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            path_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string path = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string path = 4;</code>
       */
      public Builder setPath(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string path = 4;</code>
       */
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000008);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>required string path = 4;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        path_ = value;
        onChanged();
        return this;
      }

      private long position_ ;
      /**
       * <code>required int64 position = 5;</code>
       */
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 position = 5;</code>
       */
      public long getPosition() {
        return position_;
      }
      /**
       * <code>required int64 position = 5;</code>
       */
      public Builder setPosition(long value) {
        bitField0_ |= 0x00000010;
        position_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 position = 5;</code>
       */
      public Builder clearPosition() {
        bitField0_ = (bitField0_ & ~0x00000010);
        position_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList dataMessage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDataMessageIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          dataMessage_ = new com.google.protobuf.LazyStringArrayList(dataMessage_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string dataMessage = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDataMessageList() {
        return dataMessage_.getUnmodifiableView();
      }
      /**
       * <code>repeated string dataMessage = 6;</code>
       */
      public int getDataMessageCount() {
        return dataMessage_.size();
      }
      /**
       * <code>repeated string dataMessage = 6;</code>
       */
      public String getDataMessage(int index) {
        return dataMessage_.get(index);
      }
      /**
       * <code>repeated string dataMessage = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDataMessageBytes(int index) {
        return dataMessage_.getByteString(index);
      }
      /**
       * <code>repeated string dataMessage = 6;</code>
       */
      public Builder setDataMessage(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataMessageIsMutable();
        dataMessage_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dataMessage = 6;</code>
       */
      public Builder addDataMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataMessageIsMutable();
        dataMessage_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dataMessage = 6;</code>
       */
      public Builder addAllDataMessage(
          Iterable<String> values) {
        ensureDataMessageIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dataMessage_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dataMessage = 6;</code>
       */
      public Builder clearDataMessage() {
        dataMessage_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dataMessage = 6;</code>
       */
      public Builder addDataMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataMessageIsMutable();
        dataMessage_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.DataPacket)
    }

    static {
      defaultInstance = new DataPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.DataPacket)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_DataPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_DataPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020datapacket.proto\022\010tutorial\"s\n\nDataPack" +
      "et\022\r\n\005topic\030\001 \002(\t\022\023\n\013collectTime\030\002 \002(\003\022\014" +
      "\n\004host\030\003 \002(\t\022\014\n\004path\030\004 \002(\t\022\020\n\010position\030\005" +
      " \002(\003\022\023\n\013dataMessage\030\006 \003(\tB%\n\024com.example" +
      ".tutorialB\rDataPacketMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_DataPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_DataPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_DataPacket_descriptor,
        new String[] { "Topic", "CollectTime", "Host", "Path", "Position", "DataMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
